### healthcheck
GET http://localhost:8082/ping
###
GET http://localhost:8082/moex-stocks
### create user
POST http://localhost:8082/users
Content-Type: application/json

{
  "username": "max",
  "password": "12345",
  "email": "bebeb2e@example.ru"
}


###  Login
POST http://localhost:8082/login
Content-Type: application/json

{
  "username": "max12",
  "password": "12345"
}


### Verify OTP
POST http://localhost:8082/verify-otp
Content-Type: application/json

{
  "username": "max12",
  "otp": "1531046"
}


### Get all users
GET http://localhost:8082/users



### Get news (public)
GET http://localhost:8082/news

### Create news (пока открытый, потом можно закрыть)
POST http://localhost:8082/news
Content-Type: application/json

{
  "title": "Bank 321321Kibikov запущен",
  "content": "bebebeN321312ekitLoh!"
}

### 3. Баланс  (user_id нужно подставить UUID из ответа на /users или взять из БД)
GET http://localhost:8082/balance?user_id=8953a566-57c6-4dbe-bb18-fdea80310036


### 4. Баланс
GET http://localhost:8082/balance?user_id=4a2574e5-46e8-4ef8-b558-4bb58207c24a

### Пополнение счёта пользователя
POST http://localhost:8082/deposit
role: admin
Content-Type: application/x-www-form-urlencoded

user_id=7994e089-2af2-4f40-994b-e613f82b8b22&amount=20012.00

### Списание со счёта
POST http://localhost:8082/withdraw
Content-Type: application/x-www-form-urlencoded

user_id=1135666f-a2b9-4340-94ac-6c8f77d36062&amount=200.00

### 5. Перевод 100.50
POST http://localhost:8082/transfer
Content-Type: application/x-www-form-urlencoded

from_user=8953a566-57c6-4dbe-bb18-fdea80310036&to_user=7994e089-2af2-4f40-994b-e613f82b8b22&amount=100.50


### 6. Проверка истории транзакций
GET http://localhost:8082/transactions?user_id=4a2574e5-46e8-4ef8-b558-4bb58207c24a


### 7. Проверка истории транзакций
GET http://localhost:8082/transactions?user_id=7994e089-2af2-4f40-994b-e613f82b8b22

### 8. Микрозаймы
POST http://localhost:8082/loan
Content-Type: application/json

{
  "user_id": "4a2574e5-46e8-4ef8-b558-4bb58207c24a",
  "amount": 1000
}
###
// Счетчик долгов вывести красиво
GET http://localhost:8082/loan/fc154435-9d24-42d9-9148-b088b2a52813


### Заказать такси
POST http://localhost:8082/taxi/order
Content-Type: application/json

{
  "user_id": "4a2574e5-46e8-4ef8-b558-4bb58207c24a",
  "from": "Краснаяdsadsa площадь",
  "to": "Шереметьевоdsadsa",
  "price": 500
}

### Статус заказа
GET http://localhost:8082/taxi/225282e5-49dc-4be5-b606-be808f64bb34

### История заказов пользователя
GET http://localhost:8082/taxi/history?user_id=4a2574e5-46e8-4ef8-b558-4bb58207c24a